# Generated by Django 3.0.7 on 2020-06-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='extra_info',
            field=models.CharField(default='', max_length=10),
        ),
    ]
